### ISSUE TITLE
cannot fetch "Primary Enterprise Applications" from the API

### ISSUE THREAD

**Issue by DibyodyutiMondal** [easworks/Eastalents#3]
On the page: http://localhost:4200/talentprofilequestion, in step 2

list of primary enterprise applications are fetched from the api:
https://eas-works.onrender.com/api/talentProfile/getTalentProfileSteps

this, however, yields the following error 500 response:
```json
{"status":false,"error":true,"message":"Error in getting talent profile"}
```

As a result, the dropdown is never populated

![image](https://github.com/easworks/Eastalents/assets/50345677/819dc037-a9d6-45ec-aa78-5dca7c16cb83)

**Comment by ramkrishnaindal** [comment]
Resolved

**Comment by DibyodyutiMondal** [comment]
Confirmed that the dialogs in talent profile are also working
