### ISSUE TITLE
Some data appears incorrect in the API response

### ISSUE THREAD

**Issue by DibyodyutiMondal** [easworks/Eastalents#4]
if we send a request to 
https://eas-works.onrender.com/api/talentProfile/getTalentProfileSteps,
we get back the `talentProfile` object.

Certain values in this object appear to be invalid. Specifically, certain products are like dummy objects:
```javascript
{name: '', imageUrl: ''}
```

Following are the paths to the values that I think are problematic
```json
[
    "BA/BI.Modules.Business Intelligence Tools.Product.45",
    "Collaboration.Modules.Records.Product.25",
    "CMS.Modules.Content Management.Product.20",
    "CRM.Modules.CRM.Product.31",
    "ecommerce.Modules.eCommerce Platforms.Product.47",
    "ERP.Modules.Accounts Receivable.Product.36",
    "HCM.Modules.360 Degree Feedback.Product.27",
    "PLM.Modules.Product Lifecycle Management (PLM).Product.9",
    "PLM.Modules.Fashion PLM.Product.10",
    "PLM.Modules.Manufacturing Execution System (MES).Product.40",
    "PLM.Modules.Manufacturing Software.Product.36",
    "PLM.Modules.Additive Manufacturing.Product.17",
    "PM.Modules.Project Management.Product.46",
    "PM.Modules.Team Management.Product.36",
    "SCM.Modules.Procurement.Product.23"
]
```

How should these values be treated?
Should they be dealt with client-side or backend side?

**Comment by ramkrishnaindal** [comment]
I do not find the entry
This is part of the response
Business Intelligence Tools": {
          "Product": [
            {
              "name": "Cognos Analytics",
              "imageUrl": "/images/cognos.png"
            },
            {
              "name": "Jaspersoft",
              "imageUrl": "/images/p.png"
            },
            {
              "name": "WebFOCUS",
              "imageUrl": ""
            },
            {
              "name": "Black Knight",
              "imageUrl": ""
            },
            {
              "name": "QlikView",
              "imageUrl": "/images/qlikview.png"
            },
            {
              "name": "BusinessObjects",
              "imageUrl": ""
            },
            {
              "name": "Tableau Server",
              "imageUrl": "/images/tableau.png"
            },
            {
              "name": "SQL Server",
              "imageUrl": ""
            },
            {
              "name": "Windward Reporting and Document Automation",
              "imageUrl": ""
            },
            {
              "name": "Tableau",
              "imageUrl": ""
            },
            {
              "name": "Attivio",
              "imageUrl": ""
            },
            {
              "name": "MicroStrategy",
              "imageUrl": "/images/microstrategy.png"
            },
            {
              "name": "Power BI",
              "imageUrl": ""
            },
            {
              "name": "Oracle BI",
              "imageUrl": "/images/oracle.png"
            },
            {
              "name": "Micro Focus",
              "imageUrl": ""
            },
            {
              "name": "Cloudera",
              "imageUrl": "/images/cloudera.png"
            },
            {
              "name": "Hortonworks",
              "imageUrl": ""
            },
            {
              "name": "Microsoft Dynamics GP",
              "imageUrl": "/images/microsoft.png"
            },
            {
              "name": "GoodData",
              "imageUrl": ""
            },
            {
              "name": "Spotfire",
              "imageUrl": ""
            },
            {
              "name": "Logi Analytics",
              "imageUrl": ""
            },
            {
              "name": "ibi",
              "imageUrl": "/images/ibi.png"
            },
            {
              "name": "Oracle Analytics Cloud",
              "imageUrl": "/images/oracle ana.png"
            },
            {
              "name": "Pentaho",
              "imageUrl": "/images/pentaho.png"
            },
            {
              "name": "SAP Business Analytics",
              "imageUrl": "/images/sap.png"
            },
            {
              "name": "SAP Predictive Analytics",
              "imageUrl": ""
            },
            {
              "name": "SAP Lumira",
              "imageUrl": ""
            },
            {
              "name": "Domo",
              "imageUrl": "/images/domo.png"
            },
            {
              "name": "SAS Visual Analytics",
              "imageUrl": "/images/sas.png"
            },
            {
              "name": "Altair Monarch",
              "imageUrl": ""
            },
            {
              "name": "Sisense",
              "imageUrl": ""
            },
            {
              "name": "TARGIT",
              "imageUrl": "/images/targit.png"
            },
            {
              "name": "Zendesk Explore",
              "imageUrl": "/images/zendesk.png"
            },
            {
              "name": "Zoomdata",
              "imageUrl": ""
            },
            {
              "name": "Incorta",
              "imageUrl": ""
            },
            {
              "name": "icCube",
              "imageUrl": ""
            },
            {
              "name": "Cognos Analytics",
              "imageUrl": ""
            },
            {
              "name": "Infogix",
              "imageUrl": ""
            },
            {
              "name": "Zoho Analytics",
              "imageUrl": "/images/zoho.png"
            },
            {
              "name": "ThoughtSpot",
              "imageUrl": ""
            },
            {
              "name": "ClearStory Data",
              "imageUrl": ""
            },
            {
              "name": "Jet Reports",
              "imageUrl": ""
            },
            {
              "name": "Datorama",
              "imageUrl": ""
            },
            {
              "name": "Chartio",
              "imageUrl": ""
            },
            {
              "name": "Phocas",
              "imageUrl": ""
            },
            {
              "name": "",
              "imageUrl": ""
            }
          ],

**Comment by DibyodyutiMondal** [comment]
If you see the last entry in the snippet, you'll see that the name and url are both empty strings

**Comment by DibyodyutiMondal** [comment]
For example, in this picture, there is an empty space between `AUTODESK FUSION LIFECYCLE` and `PTC FLEX PLM`.
This is caused because of empty entries. 

I could simply, filter them out client side, but the server side would still be open to the same problem, and there will be null checks required to mitigate possible errors.

![image](https://github.com/easworks/Eastalents/assets/50345677/dcc02674-fd73-4ac0-a670-e760ca5ab41a)

In my original post, the numbers at the end of the path indicate the 0-based index position of the problematic entry.

**Comment by DibyodyutiMondal** [comment]
not relevant anymore
